name: Test Workflow
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19.7.0
          registry-url: 'https://registry.npmjs.org'
      - name: "Check Publishing Required or Not"
        run: |
          cd plugin
          echo "Local Version $(node -p "require('./package.json').version")"
          echo "Server Version $(npm info react-native-sample-toast-button version)"
          if [ "$(node -p "require('./package.json').version")" != "$(npm info react-native-sample-toast-button version)" ]; then
            echo "Required Publishing"
            npm install
            npm publish
          else
            echo "Publishing Not Required"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
