name: test workflow
on: [workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 19.7.0
          registry-url: 'https://registry.npmjs.org'
      - name: "Set Version for Package"
        run: |
          if ${(npm pkg get version)} != $(npm info react-native-sample-toast-button version); then
            echo "Required Publishing"
          else
            echo "Publishing Not Required"
          fi
